# -*- coding: utf-8 -*-
"""[11/20/2022]pdf논문 텍스팅(Classifying Electoral Systems)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tdurWcFOaiGfI5GseGD6Jc9VZay1CVwv

# ** 반드시 복사해서 사용할 것!! **
"""

from google.colab import drive
drive.mount('/content/drive')

"""# tika를 활용한 pdf 텍스팅 방법"""

!pip install tika

from tika import parser # pip install tika

raw= parser.from_file('/content/drive/MyDrive/111-1Coursework/IPS558: Comparative Politics/W12/classifying-electoral-systems.pdf')  # 딕셔너리가 생성된다.
# print(type(raw))
text=raw['content']          # key 'content'의 value를 불러와서 text에 담는다.
print(text)            # text는 스트링이다.
# f=open("/content/Hall and Taylor.txt", "w")   # 필요시 파일 저장
# f.write(text)
# f.close()

text

"""## 텍스트에 제거할 부분 규칙을 찾는다

<짝수 페이지 패턴>
* \n\n\n\n52 Journal of Democracy \n\n
---
<홀수 페이지 패턴>
* \n\n\n\nJuan J .  Linz 57 \n\n
---
<공통 규칙> 모든 페이지 하단에 나오는 URL 형태가 문제가 있다->'URL'로 변환
* \n\nuse, available at https://www.cambridge.org/core/terms. https://doi.org/10.1017/9781316336182.005\nDownloaded from https://www.cambridge.org/core. YBP Library Services, on 12 Aug 2018 at 07:38:13, subject to the Cambridge Core terms of\n\n\n\n
"""

# Pre-processing
import re

text1=text.lstrip()
# text2=text1.replace("The Perils of Presidentialism \nJuan J. Linz\n\nJournal of Democracy, Volume 1, Number 1, Winter 1990, pp. 51-69 (Article)\n\nPublished by Johns Hopkins University Press\n\nFor additional information about this article\n\nAccess provided by National Sun Yat-sen University (11 May 2018 01:06 GMT)\n\nhttps://muse.jhu.edu/article/225694\n\nhttps://muse.jhu.edu/article/225694\n\n\n\n\n", 
#                     "")
# text3=text2.replace("\n\n\n\nJuan J .  Linz 5 3 \n\n", "\n\n")   # 예외적 케이스 (53->5 3으로 인식됨)
# text4=re.sub("\n\n\n\n[\d]{2} Journal of Democracy \n\n", "",text3)  # 짝수 페이지 패턴 처리
# text5=re.sub("\n\n\n\nJuan J .  Linz [\d]{2} \n\n","",text4)  # 홀수 페이지 머리말

text2=text1.replace("�","●")
text3=text2.replace("levels.\n● The constitutional","levels.\n\n● The constitutional")
text4=text3.replace("-\n", "")
text5=text4.replace("\n\n","||")  # 우선 단락 구분을 위해 \n\n를 ||로 바꿔 놓는다
text6=text5.replace("\n", " ")    # 줄바꿈 1개(\n)는 공백으로 바꿔 준다
# text=re.sub("[.][\d]{1,2}",".", text)     # 각주번호를 찾아 지운다    regex101.com에서 미리 테스트.

text6

texts=text6.split("||")   # ||로 단락을 tokenizing한다.
len(texts)

"""## 아래 코드를 실행->한글->tistory blog"""

for i in range(0,314) :
  print(texts[i], end='\n\n')